---
title: "Grundlagen Quantitative Datenanalyse"
author: "Karsten Lübke"
date: "`r Sys.Date()`"
output:
  pdf_document:
    template: null
    fig_height: 3
    fig_width: 5
    includes:
      in_header: lib/header.tex
  html_document:
    df_print: paged
documentclass: cheatsheet
papersize: a4
lang: de
classoption:
- landscape
- columns=3
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,       # In der Regel die Chunks nicht ausgeben!
  warning = FALSE)   # Warnungen überdrücken!
library(mosaic)
library(knitr)
```

## Messen

- Beim Messen wird einer Eigenschaft eines Objektes ein Wert zugewiesen. Dabei sollte die Beziehung der Werte der Beziehung der Eigenschaften der Objekte entsprechen.

- *Manifeste Variablen* können direkt gemessen werden, z. B. Größe.
- *Latente Variablen/ Konstrukte* können nicht direkt gemessen werden, sie müssen erst *operationalisiert* werden, z. B. Intelligenz.

Gütekriterien einer Messung:

- *Genauigkeit*, d. h. Exaktheit einer Messung, z. B. "Umsatz hoch/ niedrig" oder in Euro.
- *Objektivität*, d. h. Messung unabhängig vom Messenden, z. B. Kreditrating verschiedener Agenturen.
- *Reliabilität*, d. h. Zuverlässigkeit einer Messung, z. B. bei wiederholter/ anderer Messung dasselbe Ergebnis bzgl. Kundenzufriedenheit.
- *Validität*, d. h., es wird das gemessen, was gemessen werden soll, z. B. Unternehmenserfolg oder Bilanz-Kniffe.

## Skalenniveaus

*Kategoriale Skala*:

- *Nominal*: Merkmalsausprägungen können unterschieden werden, bspw. Geschlecht.
- *Ordinal*: Merkmalsausprägungen können unterschieden und in eine Reihenfolge gebracht werden, bspw. Bildungsabschlüsse. Die Abstände zwischen den Werten können nicht direkt verglichen oder interpretiert werden.

*Metrische Skala*:

Merkmalsausprägungen können unterschieden und in eine Reihenfolge gebracht werden, die Abstände sind vergleichbar.

- *Intervallskala*: Nullpunkt gesetzt, bspw. Zeitrechnung (Jahr 0).
- *Verhältnisskala*: (absoluter) Nullpunkt gegeben, bspw. Gewicht.

Weitere Unterscheidung:

- *stetig*: beliebige Zwischenwerte im Intervall sind möglich, bspw. Größe.
- *diskret*: höchstens abzählbar viele Werte sind möglich, bspw. Anzahl Kinder.

## Zusammenhangsanalyse

- *Abhängige Variable* (AV - endogen, erklärt): Wert hängt von der/ den unabhängige(n) Variable(n) ab ("$y$").
- *Unabhängige Variable* (UV - exogen, erklärend):  Wert hängt von keiner anderen Variable ab ("$x$").
- *Kovariablen*/ Störvariablen: Variablen, deren Wert ebenfalls auf die abhängige Variable einwirkt und/ oder den Zusammenhang zwischen unabhängigen und abhängigen Variablen beeinflusst ("$z$")

*Hinweis*: "$x$ steht in Zusammenhang mit $y$" heißt nicht zwangsläufig, dass $x$ kausal (ursächlich) für $y$ sein muss!

$$\text{ Daten } = \text{ Modell } + \text{ Rest}$$

## Datenerhebung

- *Population*: Die Menge, über die eine Aussage getroffen werden soll.
- *Stichprobe*: Teilmenge der Population, die zur Analyse ausgewählt wurde.
- *Stichprobenverfahren*: Prozess, mit dem die Teilmenge ausgewählt wurde.
- *Repräsentative* Stichprobe: Verteilung der Eigenschaften der Stichprobe ähnlich der in der Population? 
- *Parameter*: Wert der Population, an dem wir interessiert sind.
- *Statistik*: Wert, der auf Basis der Stichprobe berechnet wird.

$$\underbrace{\text{ Beobachteter Wert }}_{\text{Statistik}} = \underbrace{\text{ Wahrer Wert }}_{\text{Wert des Parameters}} + \text{ Verzerrung } +  \text{ Rest }$$
*Stichprobenverfahren*:

- *Zufallsstichprobe*: Jede Beobachtung die gleiche Wahrscheinlichkeit, Teil der Stichprobe zu sein.
- *Geschichtete Stichproben*: Es werden Schichten aus ähnlichen Beobachtungen gebildet (z. B. Alter, Geschlecht) und anschließend eine zufällige Stichprobe aus jeder Schicht gezogen.
- *Gelegenheitsstichproben*: Willkürliche, nicht zufällige Stichproben.


- *Beobachtungsstudien*: Es werden Daten gesammelt, ohne die Entstehung der Daten zu beeinflussen.
- *Randomisierts Experiment*:  wird der Wert der unabhängigen Variable(n) ("$x$") zufällig zugeordnet manipuliert und die Variation der abhängigen Variable ("$y$") analysisert. 

## Schlussmöglichkeiten 

\clearpage
\onecolumn

+--------------------------+--------------------------+------------------------------+
|                          | *zufällige* \            | *keine zufällige* \          |
|                          | *Zuordnung* \            | *Zuordnung* \                | 
|                          | Experiment               | Beobachtungsstudie           |
+==========================+==========================+==============================+
| *zufällige* \            | Kausalschluss, \         | kein Kausalschluss, \        |
| *Stichprobe* \           | generalisierbar \        | Aussage generalisierbar \    |
|                          | für die Population       | für die Population           |
+--------------------------+--------------------------+------------------------------+
|                          |                          |                              |
+--------------------------+--------------------------+------------------------------+
| *keine zufällige* \      | Kausalschluss, \         | kein Kausalschluss, \        |   
| *Stichprobe* \           | nur für die Stichprobe \ | Aussage nur für die \        |
| Gelegenheitsstichprobe   |                          | Stichprobe                   |
+--------------------------+--------------------------+------------------------------+

\clearpage
\twocolumn

## Quantitativer Forschungsprozess

- *Plan*: Planung der Analyse, z.B. Operationalisierung/ Variablenauswahl, Operationalisierung der Hypothesen, Wahl des Stichprobenverfahren und/ oder Versuchsplanung.
- *Data*: Datenerhebung, Datenmanagement, Datenbereinigung.
- *Analysis*: Explorative Datenanalyse, Modellierung, Hypothesenprüfung. 
- *Conclusion*: Schlussfolgerungen, Interpretation, Limitationen, neue Ideen, Kommunikation.


\columnbreak


***

**Lizenz**:  [CreativeCommons Attribution-NonCommercial-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/). 


