---
title: "Grundlagen Wissenschaft"
author: "Karsten Lübke"
date: "`r Sys.Date()`"
output:
  pdf_document:
    template: null
    fig_height: 3
    fig_width: 5
    includes:
      in_header: lib/header.tex
  html_document:
    df_print: paged
documentclass: cheatsheet
papersize: a4
lang: de
classoption:
- landscape
- columns=3
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,       # In der Regel die Chunks nicht ausgeben!
  warning = FALSE)   # Warnungen überdrücken!
library(mosaic)
library(knitr)
```

## Hypothesen

Eine Hypothese ist eine aus der Theorie oder Beobachtung abgeleitete Aussage.

- Sie sind weniger umfangreich als Theorien.
- Sie stellen Vermutungen über einen Sachverhalt an.
- Sie lassen sich überprüfen (sind also potentiell *falsifizierbar*, man kann zeigen, dass sie falsch sind). Hypothesen sind (nach Karl Popper) nie beweisbar/bestätigbar, man kann höchstens zeigen, dass sie falsch sind.

Kennzeichen einer wissenschaftlichen Hypothese:

- Sie ist eine allgemeingültige über den Einzelfall hinausgehende Behauptung.
- Häufig: $x$ hat einen Einfluss auf $y$.

## Modelle

Modelle sind vereinfachte Darstellungen relevanter Teile der Realität. Die Repräsentation der Realität durch Modelle ermöglicht eine einfachere Analyse.

- Darstellung von Modellen
  - graphisch (Pfaddiagramme)
  - verbal
  - In der Wissenschaft verwendet man häufig: *mathematisch-statistische Modelle* zur Beschreibung der Realität. 
    - Das Instrumentarium der Mathematik kann eingesetzt werden, um zu optimieren.
    - Mathematisch formulierte Modelle lassen sich gut statistisch überprüfen und ermöglichen Prognosen.
    - Statistische Modelle sind mathematische Modelle, die mit Hilfe von Daten gewonnen werden.

## Schlusstechniken

- *Induktion*:  Generalisierung von in der Realität beobachteten Regelmäßigkeiten zu einer allgemeineren Vermutung. 
- *Deduktion*:  Ableitung von Aussagen aus anderen (allgemeineren) Aussagen mit Hilfe logischer Regeln. 
- *Abduktion*: Verknüpfung von Einzelbeobachtungen und Erkennen (Vermuten) von Regeln. 

## Gütekriterien

- *Ethische Aspekte*: Können negative Folgen, z. B. bei befragten/untersuchten Personen auftreten? Auch: Datenschutz.
- *Transparenz*: Das Vorgehen ist klar dokumentiert und nachprüfbar (und damit prinzipiell *reproduzierbar*)?
- *Objektivität*: Sind die Ergebnisse unabhängig von der Person? Kommen andere zum selben Ergebnis?
- *Interne Validität*: Keine anderen Erklärungen für die Ergebnisse? Ist der behauptete Zusammenhang richtig?
- *Externe Validität*: Übertragbarkeit der Ergebnisse? Zeigt sich der behauptete Zusammenhang auch in anderen Situationen?

## Forschungsmethoden

- *Quantitative Methoden*
    - Messung und numerische Beschreibung der Wirklichkeit.
    - Allgemeingültige Gesetze für die Grundgesamtheit.
    - Ein Ausschnitt der beobachteten sozialen Vielfalt wird auf Skalen abgebildet, und es wird mit Häufigkeiten, Mittelwerten, Wahrscheinlichkeiten des Auftretens von Merkmalsausprägungen operiert.
- *Qualitative Methoden*
    - Verbalisierung der Erfahrungswirklichkeit.
    - Wirklichkeitsinterpretationen sind durch spezifische soziale Handlungsweisen geprägt und strukturieren gleichzeitig das soziale Handeln der Einzelperson vor. 
    - Untersuchungsgegenstand soll möglichst in seinem natürlichen Umfeld detailliert, ganzheitlich und umfassend erfasst werden.


\columnbreak

***

**Lizenz**:  [CreativeCommons Attribution-NonCommercial-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/). 


