on:
  push:
    branches:
      - main

name: Render and Publish

# you need these permissions to publish to GitHub pages
# permissions: 
#     contents: write
#     pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: SPECIFIC-QUARTO-VERSION-HERE
      
      # add software dependencies here and any libraries
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0' # The R version to download (if necessary) and use.

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with: 
          to: pdf

      # See more at https://github.com/quarto-dev/quarto-actions/blob/main/examples/example-03-dependencies.md

      # To publish to Netlify, RStudio Connect, or GitHub Pages, uncomment
      # the appropriate block below
      
      # - name: Publish to Netlify (and render)
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     target: netlify
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        
      # - name: Publish to RStudio Connect (and render)
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     target: connect
      #     CONNECT_SERVER: enter-the-server-url-here
      #     CONNECT_API_KEY: ${{ secrets.CONNECT_API_KEY }} 

      # NOTE: If Publishing to GitHub Pages, set the permissions correctly (see top of this yaml)
      # - name: Publish to GitHub Pages (and render) 
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     target: gh-pages
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions

      # - name: Publish to confluence
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     target: confluence
      #   env: 
      #     CONFLUENCE_USER_EMAIL: ${{ secrets.CONFLUENCE_USER_EMAIL }}
      #     CONFLUENCE_AUTH_TOKEN: ${{ secrets.CONFLUENCE_AUTH_TOKEN }}
      #     CONFLUENCE_DOMAIN: ${{ secrets.CONFLUENCE_DOMAIN }}
      
